#API keys for VirusTotal, MalwareBazaar, etc

virus_total_api_key = '<placeholder>'
malwarebazaar_api_key = '<placeholder>'
abuseipdb_api_key = '<placeholder>'
shodan_api_key = '<placeholder>'
alienvault_api_key = '<placeholder>'
ipqualityscore_api_key = '<placeholder>'
greynoise_api_key = '<placeholder>'
urlscan_api_key = '<placeholder>'
censys_api_key = '<placeholder>'
censys_secret = '<placeholder>'
binaryedge_api_key = '<placeholder>'
metadefender_api_key = '<placeholder>'
hybridanalysis_api_key = '<placeholder>'
hybridanalysis_secret = '<placeholder>'
malshare_api_key = '<placeholder>'
borealis_api_key = '63f26b5dba584f3b9e60e3f300f91238'
